# Generated by Django 4.1.7 on 2023-02-20 22:06

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Basic', max_length=50)),
                ('original_image_link', models.BooleanField(default=False)),
                ('binary_image_link', models.BooleanField(default=False)),
                ('available_hights', models.CharField(default='', help_text="Comma separated list of heights (e.g. '100,200')", max_length=200, validators=[plans.models.validate_available_hights])),
            ],
        ),
    ]
